
docker build -f docker/Dockerfile . -t victorffernandes:boilerplate
docker run --name Boilerplate -d -p 8091:8091 victorffernandes:boilerplate
docker stop Boilerplate

docker-compose -f docker/docker-compose.yml --project-directory . up -d --build