version: "3"
services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    environment:
      - NODE_ENV=production
    ports:
      - 8010:8010

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
